<a href="https://colab.research.google.com/github/KB-22/Aimi-Lab-/blob/main/Aiml_lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def sum_odd_even_cubes(num_set):
    sum_odd_cube = 0
    sum_even_cube = 0

    for num in num_set:
        if num % 2 == 0:
            sum_even_cube += num ** 3
        else:
            sum_odd_cube += num ** 3

    return sum_odd_cube, sum_even_cube

numbers = {1, 2, 3, 4, 5}
odd_cube_sum, even_cube_sum = sum_odd_even_cubes(numbers)

print("SumOddCube:", odd_cube_sum)
print("SumEvenCube:", even_cube_sum)


SumOddCube: 153
SumEvenCube: 72


In [ ]:

def matrix_operations(matrix):

    rows = len(matrix)
    cols = len(matrix[0])


    transpose = []
    for j in range(cols):
        new_row = []
        for i in range(rows):
            new_row.append(matrix[i][j])
        transpose.append(new_row)


    row_sum = []
    for row in matrix:
        total = 0
        for num in row:
            total = total + num
        row_sum.append(total)


    col_sum = []
    for j in range(cols):
        total = 0
        for i in range(rows):
            total = total + matrix[i][j]
        col_sum.append(total)

    inverse = "Inverse not possible"

    if rows == 2 and cols == 2:
        a = matrix[0][0]
        b = matrix[0][1]
        c = matrix[1][0]
        d = matrix[1][1]

        det = (a * d) - (b * c)

        if det != 0:
            inverse = [
                [ d / det, -b / det],
                [-c / det,  a / det]
            ]


    return transpose, row_sum, col_sum, inverse




matrix = [
    [1, 2],
    [3, 4]
]

transpose, row_sum, col_sum, inverse = matrix_operations(matrix)


print("Original Matrix:", matrix)
print("Transpose:", transpose)
print("Row-wise Sum:", row_sum)
print("Column-wise Sum:", col_sum)
print("Inverse:", inverse)


Original Matrix: [[1, 2], [3, 4]]
Transpose: [[1, 3], [2, 4]]
Row-wise Sum: [3, 7]
Column-wise Sum: [4, 6]
Inverse: [[-2.0, 1.0], [1.5, -0.5]]


In [ ]:
import numpy as np


A = np.array([
    [1, -2, 3],
    [-1, 3, -1],
    [2, -5, 5]
])

B = np.array([9, -6, 17])

solution = np.linalg.solve(A, B)

x = solution[0]
y = solution[1]
z = solution[2]

print("Value of x:", x)
print("Value of y:", y)
print("Value of z:", z)


Value of x: 1.0
Value of y: -1.0
Value of z: 2.0


In [ ]:
import numpy as np


arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]
], dtype=np.uint16)


print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Element size (bytes):", arr.itemsize)


Dimensions: 2
Shape: (5, 2)
Element size (bytes): 2


In [ ]:
import numpy as np

arr = np.arange(200, 300, 10, dtype=np.uint16).reshape(5, 2)

print(arr)


[[200 210]
 [220 230]
 [240 250]
 [260 270]
 [280 290]]


In [ ]:
import numpy as np


matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[2])


[7 8 9]


In [ ]:
import numpy as np

array1 = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13,14, 15, 16],
    [17,18, 19, 20]
])

array2 = array1[1::2, ::2]

print(array2)


[[ 5  7]
 [13 15]]


In [ ]:
import numpy as np

array = np.array([
    [1,  2,  3],
    [4,  5,  6],
    [7,  8,  9],
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21],
    [22, 23, 24]
])

array1, array2, array3, array4 = np.split(array, 4)

print(array1)
print(array2)
print(array3)
print(array4)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]]


In [ ]:
import numpy as np

arr = np.array([
    [16,  2,  8,  4],
    [5,  11, 10,  9],
    [12,  3, 14,  6],
    [7,  15,  1, 13]
])

sorted_by_third_row = arr[:, np.argsort(arr[2])]


sorted_by_fourth_column = arr[arr[:, 3].argsort()]

print("Sorted by third row:")
print(sorted_by_third_row)

print("\nSorted by fourth column:")
print(sorted_by_fourth_column)


Sorted by third row:
[[ 2  4 16  8]
 [11  9  5 10]
 [ 3  6 12 14]
 [15 13  7  1]]

Sorted by fourth column:
[[16  2  8  4]
 [12  3 14  6]
 [ 5 11 10  9]
 [ 7 15  1 13]]


In [ ]:
import numpy as np


arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


new_column = np.array([10, 11, 12])


arr[:, 2] = new_column

print(arr)


[[ 1  2 10]
 [ 4  5 11]
 [ 7  8 12]]


In [ ]:
# Pandas

In [ ]:
import pandas as pd
N = 5
series = pd.Series(range(1, N + 1))
print(series)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
import pandas as pd


df = pd.DataFrame({
    "A": [1, 2, 3, 4],
    "B": ["2019-05-26", "2019-05-26", "2019-05-26", "2019-05-26"],
    "C": ["Depression", "Social Anxiety", "Bipolar Disorder", "Eating Disorder"],
    "D": ["Mental health is challenging"] * 4,
    "E": ["Mental health is challenging"] * 4
})

print(df)


In [ ]:
import pandas as pd


data = {
    "A": ["Apple", "Aeroplane"],
    "B": ["Ball", "Bat"],
    "C": [None, "Cat"]
}

df = pd.DataFrame(data)

print(df)


           A     B     C
0      Apple  Ball  None
1  Aeroplane   Bat   Cat


In [ ]:
import pandas as pd

data = {
    "County": ["Ostfold", "Hordaland", "Oslo", "Hedmark", "Oppland"],
    "ISO-Code": [1, 2, 3, 4, 5],
    "Area": [4180.69, 4917.94, 454.07, 27397.76, 25192.10],
    "Administrative centre": ["Sarpsborg", "Oslo", "City of Oslo", "Hamar", "Lillehammer"]
}


df = pd.DataFrame(data)

print(df)


      County  ISO-Code      Area Administrative centre
0    Ostfold         1   4180.69             Sarpsborg
1  Hordaland         2   4917.94                  Oslo
2       Oslo         3    454.07          City of Oslo
3    Hedmark         4  27397.76                 Hamar
4    Oppland         5  25192.10           Lillehammer


In [ ]:
import pandas as pd


url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = [
    'age', 'workclass', 'fnlwgt', 'education', 'education_num',
    'marital_status', 'occupation', 'relationship', 'ethnicity',
    'gender', 'capital_gain', 'capital_loss', 'hours_per_week',
    'country_of_origin', 'income'
]

df = pd.read_csv(url, header=None, names=columns, sep=', ', engine='python')

print(df.head(10))



print("Number of rows and columns:", df.shape)
print("\nData types:")
print(df.dtypes)
print("\nMemory usage:")
print(df.memory_usage())



print("\nFirst row:")
print(df.iloc[0])

print("\nFirst 10 rows:")
print(df.head(10))

print("\nRows 10 to 15:")
print(df.iloc[10:16])


print("\nLast two rows:")
print(df.tail(2))

print("\nOdd rows from columns 3 to 5:")
print(df.iloc[1::2, 2:5])


   age         workclass  fnlwgt  education  education_num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   
5   37           Private  284582    Masters             14   
6   49           Private  160187        9th              5   
7   52  Self-emp-not-inc  209642    HS-grad              9   
8   31           Private   45781    Masters             14   
9   42           Private  159449  Bachelors             13   

          marital_status         occupation   relationship ethnicity  gender  \
0          Never-married       Adm-clerical  Not-in-family     White    Male   
1     Married-civ-spouse    Exec-managerial        Husband     White    Male   
2               Divorced  Handlers-cleaners  Not-in-family     White    Male 